// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	AdminKeyScopes  = "AdminKey.Scopes"
	TenantKeyScopes = "TenantKey.Scopes"
)

// Defines values for CreateSubscriptionRequestType.
const (
	CreateSubscriptionRequestTypeIrc   CreateSubscriptionRequestType = "irc"
	CreateSubscriptionRequestTypeSlack CreateSubscriptionRequestType = "slack"
)

// Defines values for SubscriptionType.
const (
	SubscriptionTypeIrc   SubscriptionType = "irc"
	SubscriptionTypeSlack SubscriptionType = "slack"
)

// ActiveMeeting defines model for ActiveMeeting.
type ActiveMeeting struct {
	HostId    *string    `json:"host_id,omitempty"`
	JoinUrl   *string    `json:"join_url,omitempty"`
	MeetingId string     `json:"meeting_id"`
	StartTime *time.Time `json:"start_time,omitempty"`
	TenantId  string     `json:"tenant_id"`
	Topic     *string    `json:"topic,omitempty"`
}

// AddAdminRequest defines model for AddAdminRequest.
type AddAdminRequest struct {
	SlackUserId string `json:"slack_user_id"`
}

// CreateFilterRequest defines model for CreateFilterRequest.
type CreateFilterRequest struct {
	Pattern string `json:"pattern"`
}

// CreateSubscriptionRequest defines model for CreateSubscriptionRequest.
type CreateSubscriptionRequest struct {
	IncludeLink *bool                         `json:"include_link,omitempty"`
	MeetingId   *string                       `json:"meeting_id"`
	MsgSuffix   *string                       `json:"msg_suffix,omitempty"`
	Target      string                        `json:"target"`
	Type        CreateSubscriptionRequestType `json:"type"`
}

// CreateSubscriptionRequestType defines model for CreateSubscriptionRequest.Type.
type CreateSubscriptionRequestType string

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	// Id Optional tenant ID. Generated if not provided.
	Id            *string `json:"id,omitempty"`
	TeamName      *string `json:"team_name,omitempty"`
	ZoomAccountId *string `json:"zoom_account_id,omitempty"`
}

// CreateTenantResponse defines model for CreateTenantResponse.
type CreateTenantResponse struct {
	ApiKey string `json:"api_key"`
	Id     string `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// IRCConfig defines model for IRCConfig.
type IRCConfig struct {
	Nick     string  `json:"nick"`
	Password *string `json:"password,omitempty"`
	Server   string  `json:"server"`
	TenantId *string `json:"tenant_id,omitempty"`
	UseTls   bool    `json:"use_tls"`
}

// IRCConfigRequest defines model for IRCConfigRequest.
type IRCConfigRequest struct {
	Nick     string `json:"nick"`
	Password string `json:"password"`
	Server   string `json:"server"`
	UseTls   *bool  `json:"use_tls,omitempty"`
}

// MeetingFilter defines model for MeetingFilter.
type MeetingFilter struct {
	Id       int64  `json:"id"`
	Pattern  string `json:"pattern"`
	TenantId string `json:"tenant_id"`
}

// Participant defines model for Participant.
type Participant struct {
	Email     *string    `json:"email,omitempty"`
	Id        int64      `json:"id"`
	JoinTime  *time.Time `json:"join_time,omitempty"`
	LeaveTime *time.Time `json:"leave_time"`
	MeetingId string     `json:"meeting_id"`
	UserName  string     `json:"user_name"`
}

// RotateKeyResponse defines model for RotateKeyResponse.
type RotateKeyResponse struct {
	ApiKey string `json:"api_key"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	CreatedAt   *time.Time       `json:"created_at,omitempty"`
	Enabled     bool             `json:"enabled"`
	Id          int64            `json:"id"`
	IncludeLink *bool            `json:"include_link,omitempty"`
	MeetingId   *string          `json:"meeting_id"`
	MsgSuffix   *string          `json:"msg_suffix,omitempty"`
	Target      string           `json:"target"`
	TenantId    string           `json:"tenant_id"`
	Type        SubscriptionType `json:"type"`
}

// SubscriptionType defines model for Subscription.Type.
type SubscriptionType string

// Tenant defines model for Tenant.
type Tenant struct {
	ApiKey        string     `json:"api_key"`
	Id            string     `json:"id"`
	InstalledAt   *time.Time `json:"installed_at,omitempty"`
	TeamName      *string    `json:"team_name,omitempty"`
	ZoomAccountId *string    `json:"zoom_account_id,omitempty"`
}

// TenantAdmin defines model for TenantAdmin.
type TenantAdmin struct {
	SlackUserId string `json:"slack_user_id"`
	TenantId    string `json:"tenant_id"`
}

// UpdateSubscriptionRequest defines model for UpdateSubscriptionRequest.
type UpdateSubscriptionRequest struct {
	Enabled     *bool   `json:"enabled,omitempty"`
	IncludeLink *bool   `json:"include_link,omitempty"`
	MsgSuffix   *string `json:"msg_suffix,omitempty"`
	Target      *string `json:"target,omitempty"`
}

// ZoomCredentialsRequest defines model for ZoomCredentialsRequest.
type ZoomCredentialsRequest struct {
	AccountId    string `json:"account_id"`
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}

// FilterId defines model for FilterId.
type FilterId = int64

// MeetingId defines model for MeetingId.
type MeetingId = string

// SubscriptionId defines model for SubscriptionId.
type SubscriptionId = int64

// TenantId defines model for TenantId.
type TenantId = string

// UserId defines model for UserId.
type UserId = string

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// PostWebhookZoomJSONBody defines parameters for PostWebhookZoom.
type PostWebhookZoomJSONBody = map[string]interface{}

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// AddAdminJSONRequestBody defines body for AddAdmin for application/json ContentType.
type AddAdminJSONRequestBody = AddAdminRequest

// CreateFilterJSONRequestBody defines body for CreateFilter for application/json ContentType.
type CreateFilterJSONRequestBody = CreateFilterRequest

// PutIRCConfigJSONRequestBody defines body for PutIRCConfig for application/json ContentType.
type PutIRCConfigJSONRequestBody = IRCConfigRequest

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = CreateSubscriptionRequest

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = UpdateSubscriptionRequest

// PutZoomCredentialsJSONRequestBody defines body for PutZoomCredentials for application/json ContentType.
type PutZoomCredentialsJSONRequestBody = ZoomCredentialsRequest

// PostWebhookZoomJSONRequestBody defines body for PostWebhookZoom for application/json ContentType.
type PostWebhookZoomJSONRequestBody = PostWebhookZoomJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all tenants
	// (GET /api/v1/tenants)
	ListTenants(w http.ResponseWriter, r *http.Request)
	// Create a new tenant
	// (POST /api/v1/tenants)
	CreateTenant(w http.ResponseWriter, r *http.Request)
	// Delete a tenant
	// (DELETE /api/v1/tenants/{tenantId})
	DeleteTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Get tenant details
	// (GET /api/v1/tenants/{tenantId})
	GetTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// List tenant admins
	// (GET /api/v1/tenants/{tenantId}/admins)
	ListAdmins(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Add a tenant admin
	// (POST /api/v1/tenants/{tenantId}/admins)
	AddAdmin(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Remove a tenant admin
	// (DELETE /api/v1/tenants/{tenantId}/admins/{userId})
	RemoveAdmin(w http.ResponseWriter, r *http.Request, tenantId TenantId, userId UserId)
	// List meeting filters
	// (GET /api/v1/tenants/{tenantId}/filters)
	ListFilters(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Create a meeting filter
	// (POST /api/v1/tenants/{tenantId}/filters)
	CreateFilter(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Delete a meeting filter
	// (DELETE /api/v1/tenants/{tenantId}/filters/{filterId})
	DeleteFilter(w http.ResponseWriter, r *http.Request, tenantId TenantId, filterId FilterId)
	// Get IRC configuration
	// (GET /api/v1/tenants/{tenantId}/irc)
	GetIRCConfig(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Create or update IRC configuration
	// (PUT /api/v1/tenants/{tenantId}/irc)
	PutIRCConfig(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// List active meetings
	// (GET /api/v1/tenants/{tenantId}/meetings)
	ListMeetings(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// List active participants in a meeting
	// (GET /api/v1/tenants/{tenantId}/meetings/{meetingId}/participants)
	ListParticipants(w http.ResponseWriter, r *http.Request, tenantId TenantId, meetingId MeetingId)
	// Rotate the tenant API key
	// (POST /api/v1/tenants/{tenantId}/rotate-key)
	RotateAPIKey(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// List subscriptions for a tenant
	// (GET /api/v1/tenants/{tenantId}/subscriptions)
	ListSubscriptions(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Create a subscription
	// (POST /api/v1/tenants/{tenantId}/subscriptions)
	CreateSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Delete a subscription
	// (DELETE /api/v1/tenants/{tenantId}/subscriptions/{subscriptionId})
	DeleteSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId, subscriptionId SubscriptionId)
	// Update a subscription
	// (PATCH /api/v1/tenants/{tenantId}/subscriptions/{subscriptionId})
	UpdateSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId, subscriptionId SubscriptionId)
	// Set Zoom API credentials for a tenant
	// (PUT /api/v1/tenants/{tenantId}/zoom)
	PutZoomCredentials(w http.ResponseWriter, r *http.Request, tenantId TenantId)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Receive Zoom webhook events
	// (POST /webhook/zoom)
	PostWebhookZoom(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all tenants
// (GET /api/v1/tenants)
func (_ Unimplemented) ListTenants(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new tenant
// (POST /api/v1/tenants)
func (_ Unimplemented) CreateTenant(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a tenant
// (DELETE /api/v1/tenants/{tenantId})
func (_ Unimplemented) DeleteTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get tenant details
// (GET /api/v1/tenants/{tenantId})
func (_ Unimplemented) GetTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tenant admins
// (GET /api/v1/tenants/{tenantId}/admins)
func (_ Unimplemented) ListAdmins(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a tenant admin
// (POST /api/v1/tenants/{tenantId}/admins)
func (_ Unimplemented) AddAdmin(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a tenant admin
// (DELETE /api/v1/tenants/{tenantId}/admins/{userId})
func (_ Unimplemented) RemoveAdmin(w http.ResponseWriter, r *http.Request, tenantId TenantId, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List meeting filters
// (GET /api/v1/tenants/{tenantId}/filters)
func (_ Unimplemented) ListFilters(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a meeting filter
// (POST /api/v1/tenants/{tenantId}/filters)
func (_ Unimplemented) CreateFilter(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a meeting filter
// (DELETE /api/v1/tenants/{tenantId}/filters/{filterId})
func (_ Unimplemented) DeleteFilter(w http.ResponseWriter, r *http.Request, tenantId TenantId, filterId FilterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get IRC configuration
// (GET /api/v1/tenants/{tenantId}/irc)
func (_ Unimplemented) GetIRCConfig(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update IRC configuration
// (PUT /api/v1/tenants/{tenantId}/irc)
func (_ Unimplemented) PutIRCConfig(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active meetings
// (GET /api/v1/tenants/{tenantId}/meetings)
func (_ Unimplemented) ListMeetings(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active participants in a meeting
// (GET /api/v1/tenants/{tenantId}/meetings/{meetingId}/participants)
func (_ Unimplemented) ListParticipants(w http.ResponseWriter, r *http.Request, tenantId TenantId, meetingId MeetingId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate the tenant API key
// (POST /api/v1/tenants/{tenantId}/rotate-key)
func (_ Unimplemented) RotateAPIKey(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List subscriptions for a tenant
// (GET /api/v1/tenants/{tenantId}/subscriptions)
func (_ Unimplemented) ListSubscriptions(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a subscription
// (POST /api/v1/tenants/{tenantId}/subscriptions)
func (_ Unimplemented) CreateSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a subscription
// (DELETE /api/v1/tenants/{tenantId}/subscriptions/{subscriptionId})
func (_ Unimplemented) DeleteSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId, subscriptionId SubscriptionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a subscription
// (PATCH /api/v1/tenants/{tenantId}/subscriptions/{subscriptionId})
func (_ Unimplemented) UpdateSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId, subscriptionId SubscriptionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set Zoom API credentials for a tenant
// (PUT /api/v1/tenants/{tenantId}/zoom)
func (_ Unimplemented) PutZoomCredentials(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Receive Zoom webhook events
// (POST /webhook/zoom)
func (_ Unimplemented) PostWebhookZoom(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTenants operation middleware
func (siw *ServerInterfaceWrapper) ListTenants(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTenants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTenant operation middleware
func (siw *ServerInterfaceWrapper) DeleteTenant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTenant(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenant(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdmins operation middleware
func (siw *ServerInterfaceWrapper) ListAdmins(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdmins(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddAdmin operation middleware
func (siw *ServerInterfaceWrapper) AddAdmin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAdmin(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveAdmin operation middleware
func (siw *ServerInterfaceWrapper) RemoveAdmin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveAdmin(w, r, tenantId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFilters operation middleware
func (siw *ServerInterfaceWrapper) ListFilters(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFilters(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFilter operation middleware
func (siw *ServerInterfaceWrapper) CreateFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFilter(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFilter operation middleware
func (siw *ServerInterfaceWrapper) DeleteFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "filterId" -------------
	var filterId FilterId

	err = runtime.BindStyledParameterWithOptions("simple", "filterId", chi.URLParam(r, "filterId"), &filterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filterId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFilter(w, r, tenantId, filterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIRCConfig operation middleware
func (siw *ServerInterfaceWrapper) GetIRCConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIRCConfig(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutIRCConfig operation middleware
func (siw *ServerInterfaceWrapper) PutIRCConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutIRCConfig(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMeetings operation middleware
func (siw *ServerInterfaceWrapper) ListMeetings(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMeetings(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListParticipants operation middleware
func (siw *ServerInterfaceWrapper) ListParticipants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "meetingId" -------------
	var meetingId MeetingId

	err = runtime.BindStyledParameterWithOptions("simple", "meetingId", chi.URLParam(r, "meetingId"), &meetingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "meetingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListParticipants(w, r, tenantId, meetingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) RotateAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateAPIKey(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubscriptions operation middleware
func (siw *ServerInterfaceWrapper) ListSubscriptions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubscriptions(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscription(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSubscription operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "subscriptionId" -------------
	var subscriptionId SubscriptionId

	err = runtime.BindStyledParameterWithOptions("simple", "subscriptionId", chi.URLParam(r, "subscriptionId"), &subscriptionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subscriptionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSubscription(w, r, tenantId, subscriptionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpdateSubscription(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	// ------------- Path parameter "subscriptionId" -------------
	var subscriptionId SubscriptionId

	err = runtime.BindStyledParameterWithOptions("simple", "subscriptionId", chi.URLParam(r, "subscriptionId"), &subscriptionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subscriptionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSubscription(w, r, tenantId, subscriptionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutZoomCredentials operation middleware
func (siw *ServerInterfaceWrapper) PutZoomCredentials(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tenantId" -------------
	var tenantId TenantId

	err = runtime.BindStyledParameterWithOptions("simple", "tenantId", chi.URLParam(r, "tenantId"), &tenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenantId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TenantKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutZoomCredentials(w, r, tenantId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWebhookZoom operation middleware
func (siw *ServerInterfaceWrapper) PostWebhookZoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWebhookZoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants", wrapper.ListTenants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tenants", wrapper.CreateTenant)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tenants/{tenantId}", wrapper.DeleteTenant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}", wrapper.GetTenant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}/admins", wrapper.ListAdmins)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tenants/{tenantId}/admins", wrapper.AddAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tenants/{tenantId}/admins/{userId}", wrapper.RemoveAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}/filters", wrapper.ListFilters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tenants/{tenantId}/filters", wrapper.CreateFilter)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tenants/{tenantId}/filters/{filterId}", wrapper.DeleteFilter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}/irc", wrapper.GetIRCConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/tenants/{tenantId}/irc", wrapper.PutIRCConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}/meetings", wrapper.ListMeetings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}/meetings/{meetingId}/participants", wrapper.ListParticipants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tenants/{tenantId}/rotate-key", wrapper.RotateAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/tenants/{tenantId}/subscriptions", wrapper.ListSubscriptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/tenants/{tenantId}/subscriptions", wrapper.CreateSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/tenants/{tenantId}/subscriptions/{subscriptionId}", wrapper.DeleteSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/tenants/{tenantId}/subscriptions/{subscriptionId}", wrapper.UpdateSubscription)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/tenants/{tenantId}/zoom", wrapper.PutZoomCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/webhook/zoom", wrapper.PostWebhookZoom)
	})

	return r
}

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ListTenantsRequestObject struct {
}

type ListTenantsResponseObject interface {
	VisitListTenantsResponse(w http.ResponseWriter) error
}

type ListTenants200JSONResponse []Tenant

func (response ListTenants200JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTenants401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTenants401JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTenantRequestObject struct {
	Body *CreateTenantJSONRequestBody
}

type CreateTenantResponseObject interface {
	VisitCreateTenantResponse(w http.ResponseWriter) error
}

type CreateTenant201JSONResponse CreateTenantResponse

func (response CreateTenant201JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTenant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateTenant401JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTenantRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type DeleteTenantResponseObject interface {
	VisitDeleteTenantResponse(w http.ResponseWriter) error
}

type DeleteTenant204Response struct {
}

func (response DeleteTenant204Response) VisitDeleteTenantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTenant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteTenant401JSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTenant404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteTenant404JSONResponse) VisitDeleteTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTenantRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type GetTenantResponseObject interface {
	VisitGetTenantResponse(w http.ResponseWriter) error
}

type GetTenant200JSONResponse Tenant

func (response GetTenant200JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTenant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTenant401JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetTenant404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTenant404JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListAdminsRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type ListAdminsResponseObject interface {
	VisitListAdminsResponse(w http.ResponseWriter) error
}

type ListAdmins200JSONResponse []TenantAdmin

func (response ListAdmins200JSONResponse) VisitListAdminsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAdmins401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAdmins401JSONResponse) VisitListAdminsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddAdminRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *AddAdminJSONRequestBody
}

type AddAdminResponseObject interface {
	VisitAddAdminResponse(w http.ResponseWriter) error
}

type AddAdmin201Response struct {
}

func (response AddAdmin201Response) VisitAddAdminResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AddAdmin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AddAdmin401JSONResponse) VisitAddAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RemoveAdminRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	UserId   UserId   `json:"userId"`
}

type RemoveAdminResponseObject interface {
	VisitRemoveAdminResponse(w http.ResponseWriter) error
}

type RemoveAdmin204Response struct {
}

func (response RemoveAdmin204Response) VisitRemoveAdminResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveAdmin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RemoveAdmin401JSONResponse) VisitRemoveAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RemoveAdmin404JSONResponse struct{ NotFoundJSONResponse }

func (response RemoveAdmin404JSONResponse) VisitRemoveAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListFiltersRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type ListFiltersResponseObject interface {
	VisitListFiltersResponse(w http.ResponseWriter) error
}

type ListFilters200JSONResponse []MeetingFilter

func (response ListFilters200JSONResponse) VisitListFiltersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListFilters401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListFilters401JSONResponse) VisitListFiltersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateFilterRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *CreateFilterJSONRequestBody
}

type CreateFilterResponseObject interface {
	VisitCreateFilterResponse(w http.ResponseWriter) error
}

type CreateFilter201JSONResponse MeetingFilter

func (response CreateFilter201JSONResponse) VisitCreateFilterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateFilter401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateFilter401JSONResponse) VisitCreateFilterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFilterRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	FilterId FilterId `json:"filterId"`
}

type DeleteFilterResponseObject interface {
	VisitDeleteFilterResponse(w http.ResponseWriter) error
}

type DeleteFilter204Response struct {
}

func (response DeleteFilter204Response) VisitDeleteFilterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteFilter401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteFilter401JSONResponse) VisitDeleteFilterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFilter404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteFilter404JSONResponse) VisitDeleteFilterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetIRCConfigRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type GetIRCConfigResponseObject interface {
	VisitGetIRCConfigResponse(w http.ResponseWriter) error
}

type GetIRCConfig200JSONResponse []IRCConfig

func (response GetIRCConfig200JSONResponse) VisitGetIRCConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIRCConfig401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetIRCConfig401JSONResponse) VisitGetIRCConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PutIRCConfigRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *PutIRCConfigJSONRequestBody
}

type PutIRCConfigResponseObject interface {
	VisitPutIRCConfigResponse(w http.ResponseWriter) error
}

type PutIRCConfig200JSONResponse IRCConfig

func (response PutIRCConfig200JSONResponse) VisitPutIRCConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutIRCConfig401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutIRCConfig401JSONResponse) VisitPutIRCConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListMeetingsRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type ListMeetingsResponseObject interface {
	VisitListMeetingsResponse(w http.ResponseWriter) error
}

type ListMeetings200JSONResponse []ActiveMeeting

func (response ListMeetings200JSONResponse) VisitListMeetingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMeetings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMeetings401JSONResponse) VisitListMeetingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListParticipantsRequestObject struct {
	TenantId  TenantId  `json:"tenantId"`
	MeetingId MeetingId `json:"meetingId"`
}

type ListParticipantsResponseObject interface {
	VisitListParticipantsResponse(w http.ResponseWriter) error
}

type ListParticipants200JSONResponse []Participant

func (response ListParticipants200JSONResponse) VisitListParticipantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListParticipants401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListParticipants401JSONResponse) VisitListParticipantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListParticipants404JSONResponse struct{ NotFoundJSONResponse }

func (response ListParticipants404JSONResponse) VisitListParticipantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RotateAPIKeyRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type RotateAPIKeyResponseObject interface {
	VisitRotateAPIKeyResponse(w http.ResponseWriter) error
}

type RotateAPIKey200JSONResponse RotateKeyResponse

func (response RotateAPIKey200JSONResponse) VisitRotateAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RotateAPIKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RotateAPIKey401JSONResponse) VisitRotateAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListSubscriptionsRequestObject struct {
	TenantId TenantId `json:"tenantId"`
}

type ListSubscriptionsResponseObject interface {
	VisitListSubscriptionsResponse(w http.ResponseWriter) error
}

type ListSubscriptions200JSONResponse []Subscription

func (response ListSubscriptions200JSONResponse) VisitListSubscriptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSubscriptions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSubscriptions401JSONResponse) VisitListSubscriptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscriptionRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *CreateSubscriptionJSONRequestBody
}

type CreateSubscriptionResponseObject interface {
	VisitCreateSubscriptionResponse(w http.ResponseWriter) error
}

type CreateSubscription201JSONResponse Subscription

func (response CreateSubscription201JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSubscription401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSubscription401JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSubscriptionRequestObject struct {
	TenantId       TenantId       `json:"tenantId"`
	SubscriptionId SubscriptionId `json:"subscriptionId"`
}

type DeleteSubscriptionResponseObject interface {
	VisitDeleteSubscriptionResponse(w http.ResponseWriter) error
}

type DeleteSubscription204Response struct {
}

func (response DeleteSubscription204Response) VisitDeleteSubscriptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSubscription401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteSubscription401JSONResponse) VisitDeleteSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSubscription404JSONResponse) VisitDeleteSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscriptionRequestObject struct {
	TenantId       TenantId       `json:"tenantId"`
	SubscriptionId SubscriptionId `json:"subscriptionId"`
	Body           *UpdateSubscriptionJSONRequestBody
}

type UpdateSubscriptionResponseObject interface {
	VisitUpdateSubscriptionResponse(w http.ResponseWriter) error
}

type UpdateSubscription200JSONResponse Subscription

func (response UpdateSubscription200JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscription401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateSubscription401JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSubscription404JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutZoomCredentialsRequestObject struct {
	TenantId TenantId `json:"tenantId"`
	Body     *PutZoomCredentialsJSONRequestBody
}

type PutZoomCredentialsResponseObject interface {
	VisitPutZoomCredentialsResponse(w http.ResponseWriter) error
}

type PutZoomCredentials200Response struct {
}

func (response PutZoomCredentials200Response) VisitPutZoomCredentialsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutZoomCredentials401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutZoomCredentials401JSONResponse) VisitPutZoomCredentialsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthResponse

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostWebhookZoomRequestObject struct {
	Body *PostWebhookZoomJSONRequestBody
}

type PostWebhookZoomResponseObject interface {
	VisitPostWebhookZoomResponse(w http.ResponseWriter) error
}

type PostWebhookZoom200Response struct {
}

func (response PostWebhookZoom200Response) VisitPostWebhookZoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all tenants
	// (GET /api/v1/tenants)
	ListTenants(ctx context.Context, request ListTenantsRequestObject) (ListTenantsResponseObject, error)
	// Create a new tenant
	// (POST /api/v1/tenants)
	CreateTenant(ctx context.Context, request CreateTenantRequestObject) (CreateTenantResponseObject, error)
	// Delete a tenant
	// (DELETE /api/v1/tenants/{tenantId})
	DeleteTenant(ctx context.Context, request DeleteTenantRequestObject) (DeleteTenantResponseObject, error)
	// Get tenant details
	// (GET /api/v1/tenants/{tenantId})
	GetTenant(ctx context.Context, request GetTenantRequestObject) (GetTenantResponseObject, error)
	// List tenant admins
	// (GET /api/v1/tenants/{tenantId}/admins)
	ListAdmins(ctx context.Context, request ListAdminsRequestObject) (ListAdminsResponseObject, error)
	// Add a tenant admin
	// (POST /api/v1/tenants/{tenantId}/admins)
	AddAdmin(ctx context.Context, request AddAdminRequestObject) (AddAdminResponseObject, error)
	// Remove a tenant admin
	// (DELETE /api/v1/tenants/{tenantId}/admins/{userId})
	RemoveAdmin(ctx context.Context, request RemoveAdminRequestObject) (RemoveAdminResponseObject, error)
	// List meeting filters
	// (GET /api/v1/tenants/{tenantId}/filters)
	ListFilters(ctx context.Context, request ListFiltersRequestObject) (ListFiltersResponseObject, error)
	// Create a meeting filter
	// (POST /api/v1/tenants/{tenantId}/filters)
	CreateFilter(ctx context.Context, request CreateFilterRequestObject) (CreateFilterResponseObject, error)
	// Delete a meeting filter
	// (DELETE /api/v1/tenants/{tenantId}/filters/{filterId})
	DeleteFilter(ctx context.Context, request DeleteFilterRequestObject) (DeleteFilterResponseObject, error)
	// Get IRC configuration
	// (GET /api/v1/tenants/{tenantId}/irc)
	GetIRCConfig(ctx context.Context, request GetIRCConfigRequestObject) (GetIRCConfigResponseObject, error)
	// Create or update IRC configuration
	// (PUT /api/v1/tenants/{tenantId}/irc)
	PutIRCConfig(ctx context.Context, request PutIRCConfigRequestObject) (PutIRCConfigResponseObject, error)
	// List active meetings
	// (GET /api/v1/tenants/{tenantId}/meetings)
	ListMeetings(ctx context.Context, request ListMeetingsRequestObject) (ListMeetingsResponseObject, error)
	// List active participants in a meeting
	// (GET /api/v1/tenants/{tenantId}/meetings/{meetingId}/participants)
	ListParticipants(ctx context.Context, request ListParticipantsRequestObject) (ListParticipantsResponseObject, error)
	// Rotate the tenant API key
	// (POST /api/v1/tenants/{tenantId}/rotate-key)
	RotateAPIKey(ctx context.Context, request RotateAPIKeyRequestObject) (RotateAPIKeyResponseObject, error)
	// List subscriptions for a tenant
	// (GET /api/v1/tenants/{tenantId}/subscriptions)
	ListSubscriptions(ctx context.Context, request ListSubscriptionsRequestObject) (ListSubscriptionsResponseObject, error)
	// Create a subscription
	// (POST /api/v1/tenants/{tenantId}/subscriptions)
	CreateSubscription(ctx context.Context, request CreateSubscriptionRequestObject) (CreateSubscriptionResponseObject, error)
	// Delete a subscription
	// (DELETE /api/v1/tenants/{tenantId}/subscriptions/{subscriptionId})
	DeleteSubscription(ctx context.Context, request DeleteSubscriptionRequestObject) (DeleteSubscriptionResponseObject, error)
	// Update a subscription
	// (PATCH /api/v1/tenants/{tenantId}/subscriptions/{subscriptionId})
	UpdateSubscription(ctx context.Context, request UpdateSubscriptionRequestObject) (UpdateSubscriptionResponseObject, error)
	// Set Zoom API credentials for a tenant
	// (PUT /api/v1/tenants/{tenantId}/zoom)
	PutZoomCredentials(ctx context.Context, request PutZoomCredentialsRequestObject) (PutZoomCredentialsResponseObject, error)
	// Health check
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Receive Zoom webhook events
	// (POST /webhook/zoom)
	PostWebhookZoom(ctx context.Context, request PostWebhookZoomRequestObject) (PostWebhookZoomResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListTenants operation middleware
func (sh *strictHandler) ListTenants(w http.ResponseWriter, r *http.Request) {
	var request ListTenantsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTenants(ctx, request.(ListTenantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTenants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTenantsResponseObject); ok {
		if err := validResponse.VisitListTenantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTenant operation middleware
func (sh *strictHandler) CreateTenant(w http.ResponseWriter, r *http.Request) {
	var request CreateTenantRequestObject

	var body CreateTenantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTenant(ctx, request.(CreateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTenantResponseObject); ok {
		if err := validResponse.VisitCreateTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTenant operation middleware
func (sh *strictHandler) DeleteTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request DeleteTenantRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTenant(ctx, request.(DeleteTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTenantResponseObject); ok {
		if err := validResponse.VisitDeleteTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTenant operation middleware
func (sh *strictHandler) GetTenant(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request GetTenantRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenant(ctx, request.(GetTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTenantResponseObject); ok {
		if err := validResponse.VisitGetTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAdmins operation middleware
func (sh *strictHandler) ListAdmins(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request ListAdminsRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAdmins(ctx, request.(ListAdminsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAdmins")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAdminsResponseObject); ok {
		if err := validResponse.VisitListAdminsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddAdmin operation middleware
func (sh *strictHandler) AddAdmin(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request AddAdminRequestObject

	request.TenantId = tenantId

	var body AddAdminJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddAdmin(ctx, request.(AddAdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddAdmin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddAdminResponseObject); ok {
		if err := validResponse.VisitAddAdminResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveAdmin operation middleware
func (sh *strictHandler) RemoveAdmin(w http.ResponseWriter, r *http.Request, tenantId TenantId, userId UserId) {
	var request RemoveAdminRequestObject

	request.TenantId = tenantId
	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveAdmin(ctx, request.(RemoveAdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveAdmin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveAdminResponseObject); ok {
		if err := validResponse.VisitRemoveAdminResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFilters operation middleware
func (sh *strictHandler) ListFilters(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request ListFiltersRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFilters(ctx, request.(ListFiltersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFilters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFiltersResponseObject); ok {
		if err := validResponse.VisitListFiltersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateFilter operation middleware
func (sh *strictHandler) CreateFilter(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request CreateFilterRequestObject

	request.TenantId = tenantId

	var body CreateFilterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFilter(ctx, request.(CreateFilterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFilter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFilterResponseObject); ok {
		if err := validResponse.VisitCreateFilterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFilter operation middleware
func (sh *strictHandler) DeleteFilter(w http.ResponseWriter, r *http.Request, tenantId TenantId, filterId FilterId) {
	var request DeleteFilterRequestObject

	request.TenantId = tenantId
	request.FilterId = filterId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFilter(ctx, request.(DeleteFilterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFilter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFilterResponseObject); ok {
		if err := validResponse.VisitDeleteFilterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIRCConfig operation middleware
func (sh *strictHandler) GetIRCConfig(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request GetIRCConfigRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIRCConfig(ctx, request.(GetIRCConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIRCConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIRCConfigResponseObject); ok {
		if err := validResponse.VisitGetIRCConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutIRCConfig operation middleware
func (sh *strictHandler) PutIRCConfig(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request PutIRCConfigRequestObject

	request.TenantId = tenantId

	var body PutIRCConfigJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutIRCConfig(ctx, request.(PutIRCConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutIRCConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutIRCConfigResponseObject); ok {
		if err := validResponse.VisitPutIRCConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMeetings operation middleware
func (sh *strictHandler) ListMeetings(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request ListMeetingsRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMeetings(ctx, request.(ListMeetingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMeetings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMeetingsResponseObject); ok {
		if err := validResponse.VisitListMeetingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListParticipants operation middleware
func (sh *strictHandler) ListParticipants(w http.ResponseWriter, r *http.Request, tenantId TenantId, meetingId MeetingId) {
	var request ListParticipantsRequestObject

	request.TenantId = tenantId
	request.MeetingId = meetingId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListParticipants(ctx, request.(ListParticipantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListParticipants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListParticipantsResponseObject); ok {
		if err := validResponse.VisitListParticipantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RotateAPIKey operation middleware
func (sh *strictHandler) RotateAPIKey(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request RotateAPIKeyRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RotateAPIKey(ctx, request.(RotateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RotateAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RotateAPIKeyResponseObject); ok {
		if err := validResponse.VisitRotateAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSubscriptions operation middleware
func (sh *strictHandler) ListSubscriptions(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request ListSubscriptionsRequestObject

	request.TenantId = tenantId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSubscriptions(ctx, request.(ListSubscriptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSubscriptions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSubscriptionsResponseObject); ok {
		if err := validResponse.VisitListSubscriptionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSubscription operation middleware
func (sh *strictHandler) CreateSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request CreateSubscriptionRequestObject

	request.TenantId = tenantId

	var body CreateSubscriptionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscription(ctx, request.(CreateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubscriptionResponseObject); ok {
		if err := validResponse.VisitCreateSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSubscription operation middleware
func (sh *strictHandler) DeleteSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId, subscriptionId SubscriptionId) {
	var request DeleteSubscriptionRequestObject

	request.TenantId = tenantId
	request.SubscriptionId = subscriptionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSubscription(ctx, request.(DeleteSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSubscriptionResponseObject); ok {
		if err := validResponse.VisitDeleteSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSubscription operation middleware
func (sh *strictHandler) UpdateSubscription(w http.ResponseWriter, r *http.Request, tenantId TenantId, subscriptionId SubscriptionId) {
	var request UpdateSubscriptionRequestObject

	request.TenantId = tenantId
	request.SubscriptionId = subscriptionId

	var body UpdateSubscriptionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSubscription(ctx, request.(UpdateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSubscriptionResponseObject); ok {
		if err := validResponse.VisitUpdateSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutZoomCredentials operation middleware
func (sh *strictHandler) PutZoomCredentials(w http.ResponseWriter, r *http.Request, tenantId TenantId) {
	var request PutZoomCredentialsRequestObject

	request.TenantId = tenantId

	var body PutZoomCredentialsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutZoomCredentials(ctx, request.(PutZoomCredentialsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutZoomCredentials")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutZoomCredentialsResponseObject); ok {
		if err := validResponse.VisitPutZoomCredentialsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostWebhookZoom operation middleware
func (sh *strictHandler) PostWebhookZoom(w http.ResponseWriter, r *http.Request) {
	var request PostWebhookZoomRequestObject

	var body PostWebhookZoomJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostWebhookZoom(ctx, request.(PostWebhookZoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostWebhookZoom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostWebhookZoomResponseObject); ok {
		if err := validResponse.VisitPostWebhookZoomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
